### ISSUE TITLE
TODO (post-2.0.0)

### ISSUE THREAD

**Issue by NigoroJr** [NigoroJr/zplug#1]
- [x] prezto support
- [ ] `as:completion` or somewhere along that line (`$ZPLUG_HOME/functions`)
- [ ] compile all used plugins
- [x] ~~`_zplug_dir` assoc array for tag values (rather than `zplugs`)~~
